"""hidden field form

Revision ID: 094810c36074
Revises: 0e49a5a37e59
Create Date: 2020-12-26 23:21:29.649616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094810c36074'
down_revision = '0e49a5a37e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'hidden')
    # ### end Alembic commands ###
