"""hidden field Event

Revision ID: 0e49a5a37e59
Revises: 22098466ab9c
Create Date: 2020-12-26 01:37:01.500995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e49a5a37e59'
down_revision = '22098466ab9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'hidden')
    # ### end Alembic commands ###
