"""hidden field User

Revision ID: 22098466ab9c
Revises: 0a5a1b397ef9
Create Date: 2020-12-26 00:20:25.274378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22098466ab9c'
down_revision = '0a5a1b397ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forms_signatures')
    op.add_column('users', sa.Column('hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hidden')
    op.create_table('forms_signatures',
    sa.Column('form_to_event_association_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['form_to_event_association_id'], ['form_to_event_association.id'], name='forms_signatures_form_to_event_association_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='forms_signatures_user_id_fkey')
    )
    # ### end Alembic commands ###
