"""form signatory association

Revision ID: 2f28266c98af
Revises: e0014150d336
Create Date: 2020-11-25 11:47:56.278190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f28266c98af'
down_revision = 'e0014150d336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forms_signatures')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms_signatures',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('form_to_event_association_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['form_to_event_association_id'], ['form_to_event_association.id'], name='forms_signatures_form_to_event_association_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='forms_signatures_user_id_fkey')
    )
    # ### end Alembic commands ###
