"""profile photo in user's model

Revision ID: 680314bcbfe3
Revises: c3af67d78cd0
Create Date: 2020-10-02 13:59:20.869336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680314bcbfe3'
down_revision = 'c3af67d78cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo_url')
    # ### end Alembic commands ###
