"""event's title added

Revision ID: 901ad07808f9
Revises: 09888c54b6f5
Create Date: 2020-10-06 21:23:27.311769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901ad07808f9'
down_revision = '09888c54b6f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'title')
    # ### end Alembic commands ###
