"""personal identification number

Revision ID: c3af67d78cd0
Revises: 2fc4ba706760
Create Date: 2020-09-29 12:43:04.209299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3af67d78cd0'
down_revision = '2fc4ba706760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pin')
    # ### end Alembic commands ###
