"""Form is not linked to an event

Revision ID: e0014150d336
Revises: 6e7f1a709324
Create Date: 2020-11-11 14:14:28.302121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0014150d336'
down_revision = '6e7f1a709324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('day', sa.String(), nullable=False))
    op.drop_constraint('forms_event_id_fkey', 'forms', type_='foreignkey')
    op.drop_column('forms', 'date')
    op.drop_column('forms', 'event_id')
    op.add_column('forms_signatures', sa.Column('form_to_event_association_id', sa.Integer(), nullable=True))
    op.drop_constraint('forms_signatures_form_id_fkey', 'forms_signatures', type_='foreignkey')
    op.create_foreign_key(None, 'forms_signatures', 'form_to_event_association', ['form_to_event_association_id'], ['id'])
    op.drop_column('forms_signatures', 'form_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms_signatures', sa.Column('form_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'forms_signatures', type_='foreignkey')
    op.create_foreign_key('forms_signatures_form_id_fkey', 'forms_signatures', 'forms', ['form_id'], ['id'])
    op.drop_column('forms_signatures', 'form_to_event_association_id')
    op.add_column('forms', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('forms', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.create_foreign_key('forms_event_id_fkey', 'forms', 'events', ['event_id'], ['id'])
    op.drop_column('forms', 'day')
    # ### end Alembic commands ###
