"""hidden field form_to_event_association

Revision ID: e6e627dd6544
Revises: 094810c36074
Create Date: 2020-12-27 00:23:10.578305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e627dd6544'
down_revision = '094810c36074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_to_event_association', sa.Column('hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_to_event_association', 'hidden')
    # ### end Alembic commands ###
