"""binding roles to events

Revision ID: fb9fa6b298eb
Revises: 08f994f07c84
Create Date: 2020-10-08 14:48:52.011910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb9fa6b298eb'
down_revision = '08f994f07c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_to_event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_to_event',
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event'], ['events.id'], name='user_to_event_event_fkey'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='user_to_event_user_fkey')
    )
    # ### end Alembic commands ###
